services:
  - type: web
    name: ai-agentic-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python database_setup.py && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0