services:
  - type: web
    name: ai-agent-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    branch: main
    rootDir: .
